### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by sijpkes** [open-craft/dalite-ng#62]
I'm attempting to install on a RHEL box.  I successfully installed it on an Ubuntu image last year without troubles.  I'm running Python 2.6.6.

The file that pip is complaining about is in the Pillow package. Am I missing a dependency?

```
Collecting pillow (from -r requirements/requirements.txt (line 4))
  Using cached Pillow-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5t6y2l/pillow/setup.py", line 138
        required = {'jpeg', 'zlib'}
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5t6y2l/pillow/`
```

**Comment by bradenmacdonald** [comment]
@sijpkes We don't support Python <2.7 for anything we make. Python 2.6.6 in particular has several security vulnerabilities, and "all official maintenance for Python 2.6, including security patches, has ended."

The error you're seeing here is because Pillow 4+ only supports Python 2.7 and up. You'll need to use a newer version of Python in order to run dalite-ng.

**Comment by sijpkes** [comment]
Right! I suspected that. I was already in the process of compiling Python 2.7 for that environment. Thanks @bradenmacdonald.
